name: Immersive Railroading Build Pipeline

on:
  push:
    branches:
      - 'master'
      - 'fixedNullPointer'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [1.7.10-forge, 1.10.2-forge, 1.11.2-forge, 1.12.2-forge, 1.14.4-forge, 1.15.2-forge, 1.16.5-forge, 1.17.1-forge, 1.18.2-forge, 1.19.4-forge, 1.20.1-forge]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y pngquant findutils xvfb

      - name: Setup Universal Mod Core (and helpers)
        env:
          BRANCH: ${{ matrix.branch }}
        run: java -jar UMCSetup.jar ${BRANCH} https  # Ensure this jar is in your repo or accessible

      - name: Compile with Gradle
        run: ./gradlew classes

      - name: Process images
        run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo

      - name: Run Data (Optional)
        run: xvfb-run --auto-servernum ./gradlew runData || xvfb-run --auto-servernum ./gradlew runData || true

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Maven (Optional)
        env:
          MAVENCI_PASS: ${{ secrets.MAVENCI_PASS }}  # Set this in your repository secrets
        run: ./gradlew publish

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Immersive Railroading ${{matrix.branch}}
          path: build/libs/ImmersiveRailroading-${{matrix.branch}}-*
