on:
  release:
    types: [published]

name: ImmersiveRailroading Release Build

jobs:
  build:
    name: Build & upload (${{ matrix.branch }})
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        branch: [1.7.10-forge, 1.10.2-forge, 1.11.2-forge, 1.12.2-forge, 1.14.4-forge, 1.15.2-forge, 1.16.5-forge]
      fail-fast: false

    steps:
      - name: Checkout code at the release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: temurin

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y pngquant findutils xvfb

      - name: Download LuaJ 3.0.2 JAR
        run: |
          mkdir -p libs
          curl -L -o libs/luaj-jse-3.0.2.jar https://github.com/luaj/luaj/releases/download/v3.0.2/luaj-jse-3.0.2.jar

      - name: Setup Universal Mod Core (and helpers)
        env:
          BRANCH: ${{ matrix.branch }}
        run: java -jar UMCSetup.jar ${BRANCH} https

      - name: Modify build.gradle to Include LuaJ and Merge JARs
        run: |
          {
            echo ""
            echo "repositories {"
            echo "    flatDir { dirs 'libs' }"
            echo "}"
            echo ""
            echo "dependencies {"
            echo "    implementation fileTree(dir: 'libs', include: ['*.jar'])"
            echo "}"
            echo ""
            echo "jar {"
            echo "    duplicatesStrategy = DuplicatesStrategy.EXCLUDE"
            echo "    from {"
            echo "        fileTree(dir: 'libs', include: ['*.jar']).collect { zipTree(it) }"
            echo "    }"
            echo "}"
          } >> build.gradle

      - name: Compile with Gradle
        run: ./gradlew classes --no-daemon

      - name: Process images
        run: |
          find src/main/resources/assets/immersiverailroading/ -type f -name '*.png' -print0 \
            | xargs -0 -I {} pngquant -s1 -f --ext .png {}

      - name: Build with Gradle (Including LuaJ)
        run: ./gradlew build --no-daemon

      - name: Upload JARs to this release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            build/libs/ImmersiveRailroading-${{ matrix.branch }}-*.jar
